resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolume
      name: minio-pv
    patch: |
      - op: replace
        path: /spec/hostPath/path
        value: /mnt/k8s-data/minio
    patch: |
      - op: replace
        path: /spec/capacity/storage
        value: 100Gi

  - target:
      kind: PersistentVolumeClaim
      name: minio-pvc
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 100Gi
secretGenerator:
  - name: minio-secret
    namespace: minio-dev
    envs:
      - minio.env