apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: quantlytic-kafka
  namespace: kafka
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    kraft:
      enabled: true
      controllerQuorum:
        replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      log.message.format.version: "3.7"
      inter.broker.protocol.version: "3.7"
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
