apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: quantlytic-kafka
  namespace: kafka
spec:
  kafka:
    version: 4.0.0
    replicas: 1
    kraft:
      enabled: true
      controllerQuorum:
        replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
    config:
      inter.broker.protocol.version: "4.0"
      log.message.format.version: "4.0"
  entityOperator:
    topicOperator: {}
    userOperator: {}
