name: Deploy Services to Minikube

on:
  push:
    branches:
      - main
    paths:
      - 'kafka/**'
      - 'minio/**'
      - 'timescaledb/**'

  workflow_dispatch:

jobs:
  deploy-kafka:
    name: Deploy Kafka
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy Kafka Manifests
        run: minikube kubectl -- apply -k kafka/